[package]
name = "winnow_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winnow = "0.6.13"
annotate-snippets = "0.11.4"
